# Inspection Run Workflow Template
#
# This workflow submits an inspection Job which creates `n` pod replicas and runs them in a sequence.
#
# successCondition: `n` pods have finished successfully and are present in the cluster
# failureCondition: there are more failures than is allowed (a constant to account for potential flakes)
---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: inspection-run-template
  annotations:
    thoth-station.ninja/template-version: 0.6.0
spec:
  entrypoint: main

  templates:
  - name: main
    inputs:
      parameters:
      # Required
      - name: batch-name
      - name: batch-size
      - name: inspection-id
      # Defaults
      - name: cpu
        value: "750m"
      - name: memory
        value: "1Gi"
      - name: registry
        value: docker-registry.default.svc:5000
      - name: thoth-infra-namespace
        value: "{{workflow.namespace}}"
    steps:
    - - name: job
        arguments:
          parameters:
          - name: batch-name
            value: "{{inputs.parameters.batch-name}}"
          - name: inspection-id
            value: "{{inputs.parameters.inspection-id}}"
          - name: cpu
            value: "{{inputs.parameters.cpu}}"
          - name: memory
            value: "{{inputs.parameters.memory}}"
          - name: registry
            value: "{{inputs.parameters.registry}}"
          - name: thoth-infra-namespace
            value: "{{inputs.parameters.thoth-infra-namespace}}"
          - name: item
            value: "{{item}}"
        template: create-job
        withSequence:
          count: "{{inputs.parameters.batch-size}}"

  - name: create-job
    inputs:
      parameters:
      - name: inspection-id
      - name: batch-name
      - name: cpu
      - name: memory
      - name: registry
      - name: thoth-infra-namespace
      - name: item
    initContainers:
      - name: inspect-hwinfo
        image: "{{inputs.parameters.registry}}/{{inputs.parameters.thoth-infra-namespace}}/inspect-hwinfo:latest"
        volumeMounts:
          - mountPath: "/home/amun/results/"
            name: hw-info-volume
        env:
          - name: "THOTH_OUTPUT_PATH"
            value: "/home/amun/results/{{inputs.parameters.item}}/hwinfo"
    container:
      image: "{{inputs.parameters.inspection-id}}:latest"
      env:
        - name: "THOTH_OUTPUT_PATH"
          value: "/home/amun/results/{{inputs.parameters.item}}/result"
        - name: "THOTH_AMUN_HWINFO_PATH"
          value: "/home/amun/results/{{inputs.parameters.item}}/hwinfo"
      volumeMounts:
      - mountPath: "/home/amun/results/"
        name: hw-info-volume
      resources:
        # TODO: cannot use parameters until https://github.com/argoproj/argo/issues/2412
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 1
          memory: 1Gi
        # limits:
        #   cpu: '{{inputs.parameters.cpu}}'
        #   memory: '{{inputs.parameters.memory}}'
        # requests:
        #   cpu: '{{inputs.parameters.cpu}}'
        #   memory: '{{inputs.parameters.memory}}'
    outputs:
      artifacts:
      - name: output
        path: "/home/amun/results/"
        archive:
          none: {}
    volumes:
      - name: hw-info-volume
        emptyDir: {}
