apiVersion: v1
kind: Template
metadata:
  name: amun-inspection-workflow-with-cpu
  annotations:
    description: This is Amun configuration template
    openshift.io/display-name: "Amun core components"
    version: 0.6.1
    tags: amun,argo,thoth,ai-stacks,aistacks,machinelearning,workflows
    template.openshift.io/documentation-url: https://github.com/thoth-station/
    template.openshift.io/long-description: This template defines resources needed to deploy Amun to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
  labels:
    template: amun-inspection-workflow-with-cpu
    app: amun

objects:
- kind: Workflow
  apiVersion: argoproj.io/v1alpha1
  metadata:
    name: "${AMUN_INSPECTION_ID}"
    labels:
      app: amun
      component: amun-inspection-workflow
      inspection_id: "${AMUN_INSPECTION_ID}"
    annotations:
      thoth-station.ninja/template-version: 0.6.2
  spec:
    serviceAccountName: "${ARGO_SERVICE_ACCOUNT}"

    artifactRepositoryRef:
      configMap: amun
      key: artifactRepository

    entrypoint: main

    volumes:
    - name: output-volume
      emptyDir: {}

    arguments:
      parameters:
      # Required workflow parameters
      - name: dockerfile
      - name: specification
      # Defaults
      - name: inspection-id
        value: "${AMUN_INSPECTION_ID}"
      - name: batch-size
        value: '1'
      - name: batch-name
        value: "${AMUN_INSPECTION_ID}"
      - name: allowed-failures
        value: '1'  # i.e., 99% success rate out of 100
      - name: parallelism
        value: '1'
      - name: cpu
        value: "${AMUN_CPU}"
      - name: cpu-family
        value: "${CPU_FAMILY}"
      - name: cpu-model
        value: "${CPU_MODEL}"
      - name: memory
        value: "${AMUN_MEMORY}"
      - name: physical-cpus
        value: "${PHYSICAL_CPUS}"
      - name: processor
        value: "${PROCESSOR}"
      - name: registry
        value: "${THOTH_REGISTRY}"
      - name: thoth-infra-namespace
        value: "${THOTH_INFRA_NAMESPACE}"
      # Other parameters
      - name: "target"
        value: "inspection-run-result"

    templates:
    - name: main
      dag:
        target: "{{workflow.parameters.target}}"
        tasks:
        - name: inspection-build
          arguments:
            parameters:
            - name: dockerfile
              value: '{{workflow.parameters.dockerfile}}'
            - name: specification
              value: '{{workflow.parameters.specification}}'
            - name: inspection-id
              value: "{{workflow.parameters.inspection-id}}"
            - name: allowed-failures
              value: "{{workflow.parameters.allowed-failures}}"
            - name: batch-name
              value: "{{workflow.parameters.batch-name}}"
            - name: parallelism
              value: "{{workflow.parameters.parallelism}}"
            - name: cpu
              value: "{{workflow.parameters.cpu}}"
            - name: cpu-family
              value: "{{workflow.parameters.cpu-family}}"
            - name: cpu-model
              value: "{{workflow.parameters.cpu-model}}"
            - name: memory
              value: "{{workflow.parameters.memory}}"
            - name: physical-cpus
              value: "{{workflow.parameters.physical-cpus}}"
            - name: processor
              value: "{{workflow.parameters.processor}}"
            - name: registry
              value: "{{workflow.parameters.registry}}"
            - name: thoth-infra-namespace
              value: "{{workflow.parameters.thoth-infra-namespace}}"
          templateRef:
            name: inspection-build-with-cpu-template
            template: main
          continueOn:
            failed: true

        - name: inspection-build-result
          dependencies: [inspection-build]
          arguments:
            parameters:
            - name: inspection-id
              value: "{{workflow.parameters.inspection-id}}"
            - name: exit
              value: "{{tasks.inspection-build.status}} != Succeeded"
            - name: volume
              value: output-volume
            - name: namespace
              value: "{{workflow.namespace}}"
            - name: kind
              value: pods
            - name: selector
              value: "openshift.io/build.name={{workflow.parameters.inspection-id}}-1"
            - name: registry
              value: ${THOTH_REGISTRY}
            - name: thoth-infra-namespace
              value: ${THOTH_INFRA_NAMESPACE}
            - name: dockerfile
              value: "{{workflow.parameters.dockerfile}}"
            - name: specification
              value: "{{workflow.parameters.specification}}"
          templateRef:
            name: inspection-results-template
            template: main

        - name: inspection-run
          dependencies: [inspection-build]
          arguments:
            parameters:
            - name: batch-name
              value: "{{workflow.parameters.batch-name}}"
            - name: batch-size
              value: "{{workflow.parameters.batch-size}}"
            - name: inspection-id
              value: "{{workflow.parameters.inspection-id}}"
            - name: allowed-failures
              value: "{{workflow.parameters.allowed-failures}}"
            - name: parallelism
              value: "{{workflow.parameters.parallelism}}"
            - name: cpu
              value: "{{workflow.parameters.cpu}}"
            - name: cpu-family
              value: "{{workflow.parameters.cpu-family}}"
            - name: cpu-model
              value: "{{workflow.parameters.cpu-model}}"
            - name: memory
              value: "{{workflow.parameters.memory}}"
            - name: physical-cpus
              value: "{{workflow.parameters.physical-cpus}}"
            - name: processor
              value: "{{workflow.parameters.processor}}"
            - name: registry
              value: "{{workflow.parameters.registry}}"
            - name: thoth-infra-namespace
              value: "{{workflow.parameters.thoth-infra-namespace}}"
          templateRef:
            name: inspection-run-with-cpu-template
            template: main
          continueOn:
            failed: true

        - name: inspection-run-result
          dependencies: [inspection-run]
          arguments:
            parameters:
            - name: inspection-id
              value: "{{workflow.parameters.inspection-id}}"
            - name: exit
              value: "{{tasks.inspection-run.status}} != Succeeded"
            - name: volume
              value: output-volume
            - name: namespace
              value: "{{workflow.namespace}}"
            - name: kind
              value: pods
            - name: selector
              value: "job-name={{workflow.parameters.batch-name}}"
            - name: registry
              value: ${THOTH_REGISTRY}
            - name: thoth-infra-namespace
              value: ${THOTH_INFRA_NAMESPACE}
            - name: dockerfile
              value: "{{workflow.parameters.dockerfile}}"
            - name: specification
              value: "{{workflow.parameters.specification}}"
          templateRef:
            name: inspection-results-template
            template: main

parameters:
- name: AMUN_INSPECTION_ID
  description: Id of inspection that is run.
  displayName: Inspection id
  required: true

- name: THOTH_INFRA_NAMESPACE
  description: Project where ImageStream is present
  displayName: ImageStream Project
  required: true

- name: THOTH_REGISTRY
  description: Registry server from where Image is to be pulled
  displayName: Registry
  required: true
  value: docker-registry.default.svc:5000

- name: AMUN_CPU
  description: CPU cores requested for build
  displayName: Build CPU
  value: 500m

- name: AMUN_MEMORY
  description: Memory requested for build
  displayName: Build Memory
  value: 512Mi

- name: ARGO_SERVICE_ACCOUNT
  description: Service account used by workflow steps
  displayName: Argo service account
  value: argo

- name: CPU_FAMILY
  description: Family number of CPU.
  displayName: CPU Family
  required: true

- name: CPU_MODEL
  description: Modelnumber of CPU.
  displayName: CPU model
  required: true

- name: PHYSICAL_CPUS
  description: Number of physical CPUs.
  displayName: Physical CPUS
  required: true

- name: PROCESSOR
  description: Name of processor.
  displayName: Processor name
  required: true
