apiVersion: v1
kind: Template
metadata:
  name: amun-configmap
  annotations:
    description: This is Amun config map
    openshift.io/display-name: Amun ConfigMap
    version: 0.6.0
    tags: amun,thoth,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: This template defines resources needed to deploy Amun to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.
    thoth-station.ninja/template-version: 0.6.0
  labels:
    app: amun
    template: amun-configmap
    component: configmap

objects:
  - kind: ConfigMap
    apiVersion: v1
    metadata:
      name: amun
      annotations:
        thoth-station.ninja/template-version: 0.6.0
      labels:
        app: amun
        component: configmap
    data:
      artifactRepository: |-
        archiveLogs: false

        s3:
          bucket: "{{workflow.parameters.ceph_bucket_name}}"
          endpoint: "{{workflow.parameters.ceph_host}}"
          accessKeySecret:                #omit if accessing via AWS IAM
            name: argo-artifact-repository-secrets
            key: accessKey
          secretKeySecret:                #omit if accessing via AWS IAM
            name: argo-artifact-repository-secrets
            key: secretKey
          keyFormat: >-
            {{workflow.parameters.ceph_bucket_prefix}}/
            {{workflow.parameters.deployment_name}}/
            inspection/
            {{workflow.name}}

      amun-inspection-namespace: ${AMUN_INSPECTION_NAMESPACE}
      amun-infra-namespace: ${AMUN_INFRA_NAMESPACE}
      prometheus-pushgateway-host: ${PROMETHEUS_PUSHGATEWAY_HOST}
      prometheus-pushgateway-port: ${PROMETHEUS_PUSHGATEWAY_PORT}
      metrics-pushgateway-url: ${PROMETHEUS_PUSHGATEWAY_HOST}:${PROMETHEUS_PUSHGATEWAY_PORT}

parameters:
  - description: Name of the Amun namespace where inspection is done.
    displayName: Amun Namespace
    required: true
    name: AMUN_INSPECTION_NAMESPACE

  - description: Name of the Amun namespace where templates sit.
    displayName: Amun Infra Namespace
    required: true
    name: AMUN_INFRA_NAMESPACE

  - displayName: PROMETHEUS_PUSHGATEWAY_HOST
    description: A host to push prometheus metrics via pushgateway.
    name: PROMETHEUS_PUSHGATEWAY_HOST
    required: false
    value: "pushgateway"

  - displayName: PROMETHEUS_PUSHGATEWAY_PORT
    description: A port to send prometheus metrics via pushgateway
    name: PROMETHEUS_PUSHGATEWAY_PORT
    required: false
    value: "80"
